[left]
enter_command = [ "hyprctl", "dispatch", "workspace", "r-1" ]

locations = ["bottom_left"]

size = 1
margin = 127
timeout_ms = 100
color = "#FFFF0000"  # default

[right]
enter_command = [ "hyprctl", "dispatch", "workspace", "r+1" ]

locations = ["bottom_right"]

size = 1
margin = 127
timeout_ms = 100
color = "#FFFF0000"  # default

